name: Build & Deploy Site

on:
  push:
    branches: [ main ]

permissions:
  contents: read    # for actions/checkout
  pages: write      # for deploy-pages
  id-token: write   # for authenticate-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site
        run: bundle exec jekyll build --destination _site

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1