name: CI for GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build site with Jekyll
        run: bundle exec jekyll build --destination site

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1